users:
  - first_name: "Oliver"
    last_name: "Smith"
    email: "oliver@example.com"
    password: "Welcome@123"
    role: "Admin"
  - first_name: "Eve"
    last_name: "Smith"
    email: "eve@example.com"
    password: "Welcome@123"
    role: "Standard"
  - first_name: "Rob"
    last_name: "Smith"
    email: "rob@example.com"
    password: "Welcome@123"
    role: "Admin"
