permissions:
  - name: "members.view"
    description: "View members"
    category: "Members"
  - name: "members.manage"
    description: "Manage members"
    category: "Members"
  - name: "roles.view"
    description: "View roles"
    category: "Roles"
  - name: "roles.manage"
    description: "Manage roles"
    category: "Roles"
