roles:
  - name: Admin
    permissions:
      ["members.view", "members.manage", "roles.view", "roles.manage"]
    kind: "system"
    description: "Admins can manage all members and roles"
  - name: Member
    permissions: ["members.view"]
    kind: "custom"
    description: "Members can view members"
  - name: Standard
    permissions: []
    kind: "system"
    description: "Standard users have no special permissions"
